import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_component/Navbar/Navbar";
import Footer from "./_component/Footer/Footer";
import FirstNav from "./_component/FirstNav/FirstNav";
import { Toaster } from "@/components/ui/sonner"
import MyProvider from "./_component/MyProvider/MyProvider";
import CartContextProvider from "../context/cartContext"
import { Exo } from "next/font/google";

const exo = Exo({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-exo",
  display: "swap",
});



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight:["800","600"]
});

export const metadata: Metadata = {
  title: "FreshCard",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${exo.variable} antialiased`}>
        
        <CartContextProvider>
            <MyProvider>
              <FirstNav/>
              <Navbar/>
              {children}
              <Toaster/>
              <Footer/>
          </MyProvider>
        </CartContextProvider>
        
      </body>
    </html>
  );
}
